FROM node:20-alpine

WORKDIR /app

COPY package.json package-lock.json ./
COPY frontend/package.json frontend/package.json
RUN npm ci

COPY frontend frontend

WORKDIR /app/frontend

EXPOSE 3000

CMD sh -c "npm run build && npm run serve"

