FROM node:20-alpine

WORKDIR /app

COPY package.json package-lock.json ./
COPY frontend/package.json frontend/package.json
RUN npm ci
RUN npm install -g serve

COPY frontend frontend

WORKDIR /app/frontend

EXPOSE 3000

CMD sh -c "npm run build && serve -s dist -l 3000"

